USE joinventure1;
INSERT INTO joinventure1.programmer_role (NAME) VALUES
("PRODUCT_OWNER"),
("TEAM_LEADER"),
("TECHNICAL_FRON_LEADER"),
("TECHNICAL_BACK_LEADER"),
("DATA_ENGINEER"),
("FRONT_DEVELOPER"),
("BACK_DEVELOPER"),
("FULL-STACK_DEVELOPER");

