USE joinvenTure1;

INSERT INTO joinventure1.demand (NAME) VALUES
("APP_DEVELOPMENT"),
("WEB_DEVELOPMENT"),
("SOFTWARE_DEVELOPMENT"),
("DATABASE"),
("IA"),
("IOT"),
("MACHINE_LEARNING"),
("CYBER_SECURITY");